/**
 * Network and database.
 *
 * The shape here is driven by one fact about Lambda: each concurrent container
 * owns its own Postgres pool. Fifty warm containers with `max: 5` is 250
 * connections against a t4g.micro that tops out near 80, so the database runs
 * behind **RDS Proxy**, which multiplexes them onto a small real pool.
 *
 * The VPC has no internet gateway and no NAT. Nothing here needs to reach the
 * public internet: S3 goes through a gateway endpoint, which is free, and the
 * JWKS fetch that would otherwise have forced a $32/month NAT is avoided by
 * trusting API Gateway's already-verified claims in production — option B in
 * docs/lambda-deployment-assessment.md.
 */

import {
  CfnOutput,
  Duration,
  Stack,
  type StackProps,
  aws_ec2 as ec2,
  aws_rds as rds,
} from 'aws-cdk-lib';
import type { Construct } from 'constructs';

import { type EnvConfig, resourceName } from './config.js';

export interface DataStackProps extends StackProps {
  readonly config: EnvConfig;
}

/** The database the API talks to. Matches DATABASE_URL's path component. */
const DATABASE_NAME = 'archery';

/**
 * The master user.
 *
 * One role for now. Splitting into a migration owner and a least-privilege
 * application user is the right next step, but it needs the migration runner
 * to exist first so there is something to own the schema.
 */
const DATABASE_USER = 'archery';

export class DataStack extends Stack {
  readonly vpc: ec2.Vpc;
  readonly proxy: rds.DatabaseProxy;
  readonly lambdaSecurityGroup: ec2.SecurityGroup;
  readonly databaseName = DATABASE_NAME;
  readonly databaseUser = DATABASE_USER;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    const { config } = props;

    /*
     * Isolated subnets only.
     *
     * No public subnet, no internet gateway, no NAT — so there is no route out
     * of this VPC at all. That is not just a saving: a Lambda with no egress
     * cannot be made to exfiltrate anything, whatever a future dependency
     * decides to do.
     */
    this.vpc = new ec2.Vpc(this, 'Vpc', {
      vpcName: resourceName(config, 'vpc'),
      maxAzs: config.availabilityZones,
      natGateways: 0,
      subnetConfiguration: [
        {
          name: 'isolated',
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
          cidrMask: 24,
        },
      ],
    });

    // Free, and the only way S3 is reachable from a VPC with no egress.
    this.vpc.addGatewayEndpoint('S3Endpoint', {
      service: ec2.GatewayVpcEndpointAwsService.S3,
    });

    /*
     * Three security groups in a chain: Lambda → Proxy → Database.
     *
     * Nothing can reach the database except the proxy, and nothing can reach
     * the proxy except the function. Writing it as a chain rather than one
     * shared group means a future service added to the VPC gets no database
     * access by default.
     */
    this.lambdaSecurityGroup = new ec2.SecurityGroup(this, 'LambdaSg', {
      vpc: this.vpc,
      description: 'API Lambda',
      allowAllOutbound: true,
    });

    const proxySecurityGroup = new ec2.SecurityGroup(this, 'ProxySg', {
      vpc: this.vpc,
      description: 'RDS Proxy',
      allowAllOutbound: true,
    });

    const databaseSecurityGroup = new ec2.SecurityGroup(this, 'DatabaseSg', {
      vpc: this.vpc,
      description: 'Postgres instance',
      allowAllOutbound: false,
    });

    proxySecurityGroup.addIngressRule(
      this.lambdaSecurityGroup,
      ec2.Port.tcp(5432),
      'API Lambda to RDS Proxy',
    );

    databaseSecurityGroup.addIngressRule(
      proxySecurityGroup,
      ec2.Port.tcp(5432),
      'RDS Proxy to Postgres',
    );

    /*
     * Credentials are generated by Secrets Manager and never seen by a human.
     *
     * The proxy is the only thing that reads them. The Lambda authenticates to
     * the proxy with an IAM token instead, which means no database password
     * exists in the function's environment, in the template, or in anyone's
     * shell history — and a credential rotation cannot leave the API holding a
     * stale one.
     */
    const credentials = rds.Credentials.fromGeneratedSecret(DATABASE_USER, {
      secretName: resourceName(config, 'db-credentials'),
    });

    const database = new rds.DatabaseInstance(this, 'Database', {
      instanceIdentifier: resourceName(config, 'db'),
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_16_13,
      }),
      instanceType: new ec2.InstanceType(config.databaseInstanceClass),

      vpc: this.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [databaseSecurityGroup],
      // Belt and braces alongside the isolated subnet: even if a public subnet
      // appeared later, this instance would not take an address in it.
      publiclyAccessible: false,

      credentials,
      databaseName: DATABASE_NAME,

      // Required for the proxy's IAM authentication to work end to end.
      iamAuthentication: true,

      storageEncrypted: true,
      allocatedStorage: 20,
      // Storage that grows on its own. Running out of disk takes the database
      // read-only, which for this app means an archer cannot record a session.
      maxAllocatedStorage: 100,

      multiAz: config.databaseMultiAz,
      backupRetention: config.backupRetention,
      deleteAutomatedBackups: !config.protectResources,
      deletionProtection: config.protectResources,
      removalPolicy: config.removalPolicy,

      // The client sets `rejectUnauthorized: true`, so it needs the matching
      // CA. Naming the certificate here rather than accepting the default
      // means an AWS-side rotation is a visible diff, not a surprise outage.
      caCertificate: rds.CaCertificate.RDS_CA_RSA2048_G1,

      cloudwatchLogsExports: ['postgresql'],
      enablePerformanceInsights: false,

      // Minor versions carry security fixes; a scoring app has no reason to
      // sit on an old one.
      autoMinorVersionUpgrade: true,
    });

    this.proxy = database.addProxy('Proxy', {
      dbProxyName: resourceName(config, 'db-proxy'),
      vpc: this.vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [proxySecurityGroup],
      secrets: [database.secret!],

      // No password reaches the function. See the credentials comment above.
      iamAuth: true,
      // The proxy terminates TLS from the client; requiring it means a
      // misconfigured client fails loudly rather than connecting in plaintext.
      requireTLS: true,

      /*
       * Hold a borrowed connection for at most 30 seconds.
       *
       * The default is 120. A Lambda that times out mid-transaction otherwise
       * leaves its connection pinned for two minutes, and enough of those in a
       * row exhaust the pool for everyone else.
       */
      borrowTimeout: Duration.seconds(30),
      maxConnectionsPercent: 90,
      idleClientTimeout: Duration.minutes(30),
    });

    new CfnOutput(this, 'ProxyEndpoint', {
      value: this.proxy.endpoint,
      description: 'Database host for DATABASE_URL',
    });

    new CfnOutput(this, 'DatabaseSecretArn', {
      value: database.secret!.secretArn,
      description:
        'Master credentials. Needed by the migration runner, not by the API.',
    });

    new CfnOutput(this, 'VpcId', { value: this.vpc.vpcId });
  }
}
